const en = {
  the_fool: "The Fool",
  the_magician: "The Magician",
  the_high_priestess: "The High Priestess",
  the_empress: "The Empress",
  the_emperor: "The Emperor",
  the_hierophant: "The Hierophant",
  the_lovers: "The Lovers",
  the_chariot: "The Chariot",
  strength: "Strength",
  the_hermit: "The Hermit",
  wheel_of_fortune: "Wheel of Fortune",
  justice: "Justice",
  the_hanged_man: "The Hanged Man",
  death: "Death",
  temperance: "Temperance",
  the_devil: "The Devil",
  the_tower: "The Tower",
  the_star: "The Star",
  the_moon: "The Moon",
  the_sun: "The Sun",
  judgment: "Judgment",
  the_world: "The World",
  ace_of_wands: "Ace of Wands",
  two_of_wands: "Two of Wands",
  three_of_wands: "Three of Wands",
  four_of_wands: "Four of Wands",
  five_of_wands: "Five of Wands",
  six_of_wands: "Six of Wands",
  seven_of_wands: "Seven of Wands",
  eight_of_wands: "Eight of Wands",
  nine_of_wands: "Nine of Wands",
  ten_of_wands: "Ten of Wands",
  page_of_wands: "Page of Wands",
  knight_of_wands: "Knight of Wands",
  queen_of_wands: "Queen of Wands",
  king_of_wands: "King of Wands",
  ace_of_cups: "Ace of Cups",
  two_of_cups: "Two of Cups",
  three_of_cups: "Three of Cups",
  four_of_cups: "Four of Cups",
  five_of_cups: "Five of Cups",
  six_of_cups: "Six of Cups",
  seven_of_cups: "Seven of Cups",
  eight_of_cups: "Eight of Cups",
  nine_of_cups: "Nine of Cups",
  ten_of_cups: "Ten of Cups",
  page_of_cups: "Page of Cups",
  knight_of_cups: "Knight of Cups",
  queen_of_cups: "Queen of Cups",
  king_of_cups: "King of Cups",
  ace_of_swords: "Ace of Swords",
  two_of_swords: "Two of Swords",
  three_of_swords: "Three of Swords",
  four_of_swords: "Four of Swords",
  five_of_swords: "Five of Swords",
  six_of_swords: "Six of Swords",
  seven_of_swords: "Seven of Swords",
  eight_of_swords: "Eight of Swords",
  nine_of_swords: "Nine of Swords",
  ten_of_swords: "Ten of Swords",
  page_of_swords: "Page of Swords",
  knight_of_swords: "Knight of Swords",
  queen_of_swords: "Queen of Swords",
  king_of_swords: "King of Swords",
  ace_of_pentacles: "Ace of Pentacles",
  two_of_pentacles: "Two of Pentacles",
  three_of_pentacles: "Three of Pentacles",
  four_of_pentacles: "Four of Pentacles",
  five_of_pentacles: "Five of Pentacles",
  six_of_pentacles: "Six of Pentacles",
  seven_of_pentacles: "Seven of Pentacles",
  eight_of_pentacles: "Eight of Pentacles",
  nine_of_pentacles: "Nine of Pentacles",
  ten_of_pentacles: "Ten of Pentacles",
  page_of_pentacles: "Page of Pentacles",
  knight_of_pentacles: "Knight of Pentacles",
  queen_of_pentacles: "Queen of Pentacles",
  king_of_pentacles: "King of Pentacles",
  the_fool_reversed: "The Fool Reversed",
  the_magician_reversed: "The Magician Reversed",
  the_high_priestess_reversed: "The High Priestess Reversed",
  the_empress_reversed: "The Empress Reversed",
  the_emperor_reversed: "The Emperor Reversed",
  the_hierophant_reversed: "The Hierophant Reversed",
  the_lovers_reversed: "The Lovers Reversed",
  the_chariot_reversed: "The Chariot Reversed",
  strength_reversed: "Strength Reversed",
  the_hermit_reversed: "The Hermit Reversed",
  wheel_of_fortune_reversed: "Wheel of Fortune Reversed",
  justice_reversed: "Justice Reversed",
  the_hanged_man_reversed: "The Hanged Man Reversed",
  death_reversed: "Death Reversed",
  temperance_reversed: "Temperance Reversed",
  the_devil_reversed: "The Devil Reversed",
  the_tower_reversed: "The Tower Reversed",
  the_star_reversed: "The Star Reversed",
  the_moon_reversed: "The Moon Reversed",
  the_sun_reversed: "The Sun Reversed",
  judgment_reversed: "Judgment Reversed",
  the_world_reversed: "The World Reversed",
  ace_of_wands_reversed: "Ace of Wands Reversed",
  two_of_wands_reversed: "Two of Wands Reversed",
  three_of_wands_reversed: "Three of Wands Reversed",
  four_of_wands_reversed: "Four of Wands Reversed",
  five_of_wands_reversed: "Five of Wands Reversed",
  six_of_wands_reversed: "Six of Wands Reversed",
  seven_of_wands_reversed: "Seven of Wands Reversed",
  eight_of_wands_reversed: "Eight of Wands Reversed",
  nine_of_wands_reversed: "Nine of Wands Reversed",
  ten_of_wands_reversed: "Ten of Wands Reversed",
  page_of_wands_reversed: "Page of Wands Reversed",
  knight_of_wands_reversed: "Knight of Wands Reversed",
  queen_of_wands_reversed: "Queen of Wands Reversed",
  king_of_wands_reversed: "King of Wands Reversed",
  ace_of_cups_reversed: "Ace of Cups Reversed",
  two_of_cups_reversed: "Two of Cups Reversed",
  three_of_cups_reversed: "Three of Cups Reversed",
  four_of_cups_reversed: "Four of Cups Reversed",
  five_of_cups_reversed: "Five of Cups Reversed",
  six_of_cups_reversed: "Six of Cups Reversed",
  seven_of_cups_reversed: "Seven of Cups Reversed",
  eight_of_cups_reversed: "Eight of Cups Reversed",
  nine_of_cups_reversed: "Nine of Cups Reversed",
  ten_of_cups_reversed: "Ten of Cups Reversed",
  page_of_cups_reversed: "Page of Cups Reversed",
  knight_of_cups_reversed: "Knight of Cups Reversed",
  queen_of_cups_reversed: "Queen of Cups Reversed",
  king_of_cups_reversed: "King of Cups Reversed",
  ace_of_swords_reversed: "Ace of Swords Reversed",
  two_of_swords_reversed: "Two of Swords Reversed",
  three_of_swords_reversed: "Three of Swords Reversed",
  four_of_swords_reversed: "Four of Swords Reversed",
  five_of_swords_reversed: "Five of Swords Reversed",
  six_of_swords_reversed: "Six of Swords Reversed",
  seven_of_swords_reversed: "Seven of Swords Reversed",
  eight_of_swords_reversed: "Eight of Swords Reversed",
  nine_of_swords_reversed: "Nine of Swords Reversed",
  ten_of_swords_reversed: "Ten of Swords Reversed",
  page_of_swords_reversed: "Page of Swords Reversed",
  knight_of_swords_reversed: "Knight of Swords Reversed",
  queen_of_swords_reversed: "Queen of Swords Reversed",
  king_of_swords_reversed: "King of Swords Reversed",
  ace_of_pentacles_reversed: "Ace of Pentacles Reversed",
  two_of_pentacles_reversed: "Two of Pentacles Reversed",
  three_of_pentacles_reversed: "Three of Pentacles Reversed",
  four_of_pentacles_reversed: "Four of Pentacles Reversed",
  five_of_pentacles_reversed: "Five of Pentacles Reversed",
  six_of_pentacles_reversed: "Six of Pentacles Reversed",
  seven_of_pentacles_reversed: "Seven of Pentacles Reversed",
  eight_of_pentacles_reversed: "Eight of Pentacles Reversed",
  nine_of_pentacles_reversed: "Nine of Pentacles Reversed",
  ten_of_pentacles_reversed: "Ten of Pentacles Reversed",
  page_of_pentacles_reversed: "Page of Pentacles Reversed",
  knight_of_pentacles_reversed: "Knight of Pentacles Reversed",
  queen_of_pentacles_reversed: "Queen of Pentacles Reversed",
  king_of_pentacles_reversed: "King of Pentacles Reversed",
} as const;

const ru = {
  the_fool: "Дурак",
  the_magician: "Маг",
  the_high_priestess: "Жрица",
  the_empress: "Императрица",
  the_emperor: "Император",
  the_hierophant: "Иерофант",
  the_lovers: "Влюбленные",
  the_chariot: "Колесница",
  strength: "Сила",
  the_hermit: "Отшельник",
  wheel_of_fortune: "Колесо Фортуны",
  justice: "Справедливость",
  the_hanged_man: "Повешенный",
  death: "Смерть",
  temperance: "Умеренность",
  the_devil: "Дьявол",
  the_tower: "Башня",
  the_star: "Звезда",
  the_moon: "Луна",
  the_sun: "Солнце",
  judgment: "Суд",
  the_world: "Мир",
  ace_of_wands: "Туз Жезлов",
  two_of_wands: "Двойка Жезлов",
  three_of_wands: "Тройка Жезлов",
  four_of_wands: "Четверка Жезлов",
  five_of_wands: "Пятерка Жезлов",
  six_of_wands: "Шестерка Жезлов",
  seven_of_wands: "Семерка Жезлов",
  eight_of_wands: "Восьмерка Жезлов",
  nine_of_wands: "Девятка Жезлов",
  ten_of_wands: "Десятка Жезлов",
  page_of_wands: "Паж Жезлов",
  knight_of_wands: "Рыцарь Жезлов",
  queen_of_wands: "Королева Жезлов",
  king_of_wands: "Король Жезлов",
  ace_of_cups: "Туз Кубков",
  two_of_cups: "Двойка Кубков",
  three_of_cups: "Тройка Кубков",
  four_of_cups: "Четверка Кубков",
  five_of_cups: "Пятерка Кубков",
  six_of_cups: "Шестерка Кубков",
  seven_of_cups: "Семерка Кубков",
  eight_of_cups: "Восьмерка Кубков",
  nine_of_cups: "Девятка Кубков",
  ten_of_cups: "Десятка Кубков",
  page_of_cups: "Паж Кубков",
  knight_of_cups: "Рыцарь Кубков",
  queen_of_cups: "Королева Кубков",
  king_of_cups: "Король Кубков",
  ace_of_swords: "Туз Мечей",
  two_of_swords: "Двойка Мечей",
  three_of_swords: "Тройка Мечей",
  four_of_swords: "Четверка Мечей",
  five_of_swords: "Пятерка Мечей",
  six_of_swords: "Шестерка Мечей",
  seven_of_swords: "Семерка Мечей",
  eight_of_swords: "Восьмерка Мечей",
  nine_of_swords: "Девятка Мечей",
  ten_of_swords: "Десятка Мечей",
  page_of_swords: "Паж Мечей",
  knight_of_swords: "Рыцарь Мечей",
  queen_of_swords: "Королева Мечей",
  king_of_swords: "Король Мечей",
  ace_of_pentacles: "Туз Пентаклей",
  two_of_pentacles: "Двойка Пентаклей",
  three_of_pentacles: "Тройка Пентаклей",
  four_of_pentacles: "Четверка Пентаклей",
  five_of_pentacles: "Пятерка Пентаклей",
  six_of_pentacles: "Шестерка Пентаклей",
  seven_of_pentacles: "Семерка Пентаклей",
  eight_of_pentacles: "Восьмерка Пентаклей",
  nine_of_pentacles: "Девятка Пентаклей",
  ten_of_pentacles: "Десятка Пентаклей",
  page_of_pentacles: "Паж Пентаклей",
  knight_of_pentacles: "Рыцарь Пентаклей",
  queen_of_pentacles: "Королева Пентаклей",
  king_of_pentacles: "Король Пентаклей",
  the_fool_reversed: "Шут Перевернутый",
  the_magician_reversed: "Маг Перевернутый",
  the_high_priestess_reversed: "Верховная Жрица Перевернутая",
  the_empress_reversed: "Императрица Перевернутая",
  the_emperor_reversed: "Император Перевернутый",
  the_hierophant_reversed: "Иерофант Перевернутый",
  the_lovers_reversed: "Влюбленные Перевернутые",
  the_chariot_reversed: "Колесница Перевернутая",
  strength_reversed: "Сила Перевернутая",
  the_hermit_reversed: "Отшельник Перевернутый",
  wheel_of_fortune_reversed: "Колесо Фортуны Перевернутое",
  justice_reversed: "Справедливость Перевернутая",
  the_hanged_man_reversed: "Повешенный Перевернутый",
  death_reversed: "Смерть Перевернутая",
  temperance_reversed: "Умеренность Перевернутая",
  the_devil_reversed: "Дьявол Перевернутый",
  the_tower_reversed: "Башня Перевернутая",
  the_star_reversed: "Звезда Перевернутая",
  the_moon_reversed: "Луна Перевернутая",
  the_sun_reversed: "Солнце Перевернутое",
  judgment_reversed: "Суд Перевернутый",
  the_world_reversed: "Мир Перевернутый",
  ace_of_wands_reversed: "Туз Жезлов Перевернутый",
  two_of_wands_reversed: "Двойка Жезлов Перевернутая",
  three_of_wands_reversed: "Тройка Жезлов Перевернутая",
  four_of_wands_reversed: "Четверка Жезлов Перевернутая",
  five_of_wands_reversed: "Пятерка Жезлов Перевернутая",
  six_of_wands_reversed: "Шестерка Жезлов Перевернутая",
  seven_of_wands_reversed: "Семерка Жезлов Перевернутая",
  eight_of_wands_reversed: "Восьмерка Жезлов Перевернутая",
  nine_of_wands_reversed: "Девятка Жезлов Перевернутая",
  ten_of_wands_reversed: "Десятка Жезлов Перевернутая",
  page_of_wands_reversed: "Паж Жезлов Перевернутый",
  knight_of_wands_reversed: "Рыцарь Жезлов Перевернутый",
  queen_of_wands_reversed: "Королева Жезлов Перевернутая",
  king_of_wands_reversed: "Король Жезлов Перевернутый",
  ace_of_cups_reversed: "Туз Кубков Перевернутый",
  two_of_cups_reversed: "Двойка Кубков Перевернутая",
  three_of_cups_reversed: "Тройка Кубков Перевернутая",
  four_of_cups_reversed: "Четверка Кубков Перевернутая",
  five_of_cups_reversed: "Пятерка Кубков Перевернутая",
  six_of_cups_reversed: "Шестерка Кубков Перевернутая",
  seven_of_cups_reversed: "Семерка Кубков Перевернутая",
  eight_of_cups_reversed: "Восьмерка Кубков Перевернутая",
  nine_of_cups_reversed: "Девятка Кубков Перевернутая",
  ten_of_cups_reversed: "Десятка Кубков Перевернутая",
  page_of_cups_reversed: "Паж Кубков Перевернутый",
  knight_of_cups_reversed: "Рыцарь Кубков Перевернутый",
  queen_of_cups_reversed: "Королева Кубков Перевернутая",
  king_of_cups_reversed: "Король Кубков Перевернутый",
  ace_of_swords_reversed: "Туз Мечей Перевернутый",
  two_of_swords_reversed: "Двойка Мечей Перевернутая",
  three_of_swords_reversed: "Тройка Мечей Перевернутая",
  four_of_swords_reversed: "Четверка Мечей Перевернутая",
  five_of_swords_reversed: "Пятерка Мечей Перевернутая",
  six_of_swords_reversed: "Шестерка Мечей Перевернутая",
  seven_of_swords_reversed: "Семерка Мечей Перевернутая",
  eight_of_swords_reversed: "Восьмерка Мечей Перевернутая",
  nine_of_swords_reversed: "Девятка Мечей Перевернутая",
  ten_of_swords_reversed: "Десятка Мечей Перевернутая",
  page_of_swords_reversed: "Паж Мечей Перевернутый",
  knight_of_swords_reversed: "Рыцарь Мечей Перевернутый",
  queen_of_swords_reversed: "Королева Мечей Перевернутая",
  king_of_swords_reversed: "Король Мечей Перевернутый",
  ace_of_pentacles_reversed: "Туз Пентаклей Перевернутый",
  two_of_pentacles_reversed: "Двойка Пентаклей Перевернутая",
  three_of_pentacles_reversed: "Тройка Пентаклей Перевернутая",
  four_of_pentacles_reversed: "Четверка Пентаклей Перевернутая",
  five_of_pentacles_reversed: "Пятерка Пентаклей Перевернутая",
  six_of_pentacles_reversed: "Шестерка Пентаклей Перевернутая",
  seven_of_pentacles_reversed: "Семерка Пентаклей Перевернутая",
  eight_of_pentacles_reversed: "Восьмерка Пентаклей Перевернутая",
  nine_of_pentacles_reversed: "Девятка Пентаклей Перевернутая",
  ten_of_pentacles_reversed: "Десятка Пентаклей Перевернутая",
  page_of_pentacles_reversed: "Паж Пентаклей Перевернутый",
  knight_of_pentacles_reversed: "Рыцарь Пентаклей Перевернутый",
  queen_of_pentacles_reversed: "Королева Пентаклей Перевернутая",
  king_of_pentacles_reversed: "Король Пентаклей Перевернутый",
} as const;

const uk = {
  the_fool: "Дурень",
  the_magician: "Маг",
  the_high_priestess: "Жриця",
  the_empress: "Імператриця",
  the_emperor: "Імператор",
  the_hierophant: "Ієрофант",
  the_lovers: "Закохані",
  the_chariot: "Колісниця",
  strength: "Сила",
  the_hermit: "Відлюдник",
  wheel_of_fortune: "Колесо Фортуни",
  justice: "Справедливість",
  the_hanged_man: "Повішений",
  death: "Смерть",
  temperance: "Помірність",
  the_devil: "Диявол",
  the_tower: "Вежа",
  the_star: "Зірка",
  the_moon: "Місяць",
  the_sun: "Сонце",
  judgment: "Суд",
  the_world: "Світ",
  ace_of_wands: "Туз Жезлів",
  two_of_wands: "Двійка Жезлів",
  three_of_wands: "Трійка Жезлів",
  four_of_wands: "Четвірка Жезлів",
  five_of_wands: "П’ятірка Жезлів",
  six_of_wands: "Шістка Жезлів",
  seven_of_wands: "Сімка Жезлів",
  eight_of_wands: "Вісімка Жезлів",
  nine_of_wands: "Дев’ятка Жезлів",
  ten_of_wands: "Десятка Жезлів",
  page_of_wands: "Паж Жезлів",
  knight_of_wands: "Лицар Жезлів",
  queen_of_wands: "Королева Жезлів",
  king_of_wands: "Король Жезлів",
  ace_of_cups: "Туз Кубків",
  two_of_cups: "Двійка Кубків",
  three_of_cups: "Трійка Кубків",
  four_of_cups: "Четвірка Кубків",
  five_of_cups: "П’ятірка Кубків",
  six_of_cups: "Шістка Кубків",
  seven_of_cups: "Сімка Кубків",
  eight_of_cups: "Вісімка Кубків",
  nine_of_cups: "Дев’ятка Кубків",
  ten_of_cups: "Десятка Кубків",
  page_of_cups: "Паж Кубків",
  knight_of_cups: "Лицар Кубків",
  queen_of_cups: "Королева Кубків",
  king_of_cups: "Король Кубків",
  ace_of_swords: "Туз Мечів",
  two_of_swords: "Двійка Мечів",
  three_of_swords: "Трійка Мечів",
  four_of_swords: "Четвірка Мечів",
  five_of_swords: "П’ятірка Мечів",
  six_of_swords: "Шістка Мечів",
  seven_of_swords: "Сімка Мечів",
  eight_of_swords: "Вісімка Мечів",
  nine_of_swords: "Дев’ятка Мечів",
  ten_of_swords: "Десятка Мечів",
  page_of_swords: "Паж Мечів",
  knight_of_swords: "Лицар Мечів",
  queen_of_swords: "Королева Мечів",
  king_of_swords: "Король Мечів",
  ace_of_pentacles: "Туз Пентаклів",
  two_of_pentacles: "Двійка Пентаклів",
  three_of_pentacles: "Трійка Пентаклів",
  four_of_pentacles: "Четвірка Пентаклів",
  five_of_pentacles: "П’ятірка Пентаклів",
  six_of_pentacles: "Шістка Пентаклів",
  seven_of_pentacles: "Сімка Пентаклів",
  eight_of_pentacles: "Вісімка Пентаклів",
  nine_of_pentacles: "Дев’ятка Пентаклів",
  ten_of_pentacles: "Десятка Пентаклів",
  page_of_pentacles: "Паж Пентаклів",
  knight_of_pentacles: "Лицар Пентаклів",
  queen_of_pentacles: "Королева Пентаклів",
  king_of_pentacles: "Король Пентаклів",
  the_fool_reversed: "Дурень Перевернутий",
  the_magician_reversed: "Маг Перевернутий",
  the_high_priestess_reversed: "Верховна Жриця Перевернута",
  the_empress_reversed: "Імператриця Перевернута",
  the_emperor_reversed: "Імператор Перевернутий",
  the_hierophant_reversed: "Ієрофант Перевернутий",
  the_lovers_reversed: "Коханці Перевернуті",
  the_chariot_reversed: "Колісниця Перевернута",
  strength_reversed: "Сила Перевернута",
  the_hermit_reversed: "Відлюдник Перевернутий",
  wheel_of_fortune_reversed: "Колесо Фортуни Перевернуте",
  justice_reversed: "Справедливість Перевернута",
  the_hanged_man_reversed: "Повішений Перевернутий",
  death_reversed: "Смерть Перевернута",
  temperance_reversed: "Помірність Перевернута",
  the_devil_reversed: "Диявол Перевернутий",
  the_tower_reversed: "Вежа Перевернута",
  the_star_reversed: "Зірка Перевернута",
  the_moon_reversed: "Місяць Перевернутий",
  the_sun_reversed: "Сонце Перевернуте",
  judgment_reversed: "Суд Перевернутий",
  the_world_reversed: "Світ Перевернутий",
  ace_of_wands_reversed: "Туз Жезлів Перевернутий",
  two_of_wands_reversed: "Двійка Жезлів Перевернута",
  three_of_wands_reversed: "Трійка Жезлів Перевернута",
  four_of_wands_reversed: "Четвірка Жезлів Перевернута",
  five_of_wands_reversed: "П'ятірка Жезлів Перевернута",
  six_of_wands_reversed: "Шістка Жезлів Перевернута",
  seven_of_wands_reversed: "Сімка Жезлів Перевернута",
  eight_of_wands_reversed: "Вісімка Жезлів Перевернута",
  nine_of_wands_reversed: "Дев'ятка Жезлів Перевернута",
  ten_of_wands_reversed: "Десятка Жезлів Перевернута",
  page_of_wands_reversed: "Паж Жезлів Перевернутий",
  knight_of_wands_reversed: "Лицар Жезлів Перевернутий",
  queen_of_wands_reversed: "Королева Жезлів Перевернута",
  king_of_wands_reversed: "Король Жезлів Перевернутий",
  ace_of_cups_reversed: "Туз Кубків Перевернутий",
  two_of_cups_reversed: "Двійка Кубків Перевернута",
  three_of_cups_reversed: "Трійка Кубків Перевернута",
  four_of_cups_reversed: "Четвірка Кубків Перевернута",
  five_of_cups_reversed: "П'ятірка Кубків Перевернута",
  six_of_cups_reversed: "Шістка Кубків Перевернута",
  seven_of_cups_reversed: "Сімка Кубків Перевернута",
  eight_of_cups_reversed: "Вісімка Кубків Перевернута",
  nine_of_cups_reversed: "Дев'ятка Кубків Перевернута",
  ten_of_cups_reversed: "Десятка Кубків Перевернута",
  page_of_cups_reversed: "Паж Кубків Перевернутий",
  knight_of_cups_reversed: "Лицар Кубків Перевернутий",
  queen_of_cups_reversed: "Королева Кубків Перевернута",
  king_of_cups_reversed: "Король Кубків Перевернутий",
  ace_of_swords_reversed: "Туз Мечів Перевернутий",
  two_of_swords_reversed: "Двійка Мечів Перевернута",
  three_of_swords_reversed: "Трійка Мечів Перевернута",
  four_of_swords_reversed: "Четвірка Мечів Перевернута",
  five_of_swords_reversed: "П'ятірка Мечів Перевернута",
  six_of_swords_reversed: "Шістка Мечів Перевернута",
  seven_of_swords_reversed: "Сімка Мечів Перевернута",
  eight_of_swords_reversed: "Вісімка Мечів Перевернута",
  nine_of_swords_reversed: "Дев'ятка Мечів Перевернута",
  ten_of_swords_reversed: "Десятка Мечів Перевернута",
  page_of_swords_reversed: "Паж Мечів Перевернутий",
  knight_of_swords_reversed: "Лицар Мечів Перевернутий",
  queen_of_swords_reversed: "Королева Мечів Перевернута",
  king_of_swords_reversed: "Король Мечів Перевернутий",
  ace_of_pentacles_reversed: "Туз Пентаклів Перевернутий",
  two_of_pentacles_reversed: "Двійка Пентаклів Перевернута",
  three_of_pentacles_reversed: "Трійка Пентаклів Перевернута",
  four_of_pentacles_reversed: "Четвірка Пентаклів Перевернута",
  five_of_pentacles_reversed: "П'ятірка Пентаклів Перевернута",
  six_of_pentacles_reversed: "Шістка Пентаклів Перевернута",
  seven_of_pentacles_reversed: "Сімка Пентаклів Перевернута",
  eight_of_pentacles_reversed: "Вісімка Пентаклів Перевернута",
  nine_of_pentacles_reversed: "Дев'ятка Пентаклів Перевернута",
  ten_of_pentacles_reversed: "Десятка Пентаклів Перевернута",
  page_of_pentacles_reversed: "Паж Пентаклів Перевернутий",
  knight_of_pentacles_reversed: "Лицар Пентаклів Перевернутий",
  queen_of_pentacles_reversed: "Королева Пентаклів Перевернута",
  king_of_pentacles_reversed: "Король Пентаклів Перевернутий",
} as const;

export const cards = {
  en: en,
  uk: uk,
  ru: ru,
};
