const english = {
  the_fool: "The Fool",
  the_magician: "The Magician",
  the_high_priestess: "The High Priestess",
  the_empress: "The Empress",
  the_emperor: "The Emperor",
  the_hierophant: "The Hierophant",
  the_lovers: "The Lovers",
  the_chariot: "The Chariot",
  strength: "Strength",
  the_hermit: "The Hermit",
  wheel_of_fortune: "Wheel of Fortune",
  justice: "Justice",
  the_hanged_man: "The Hanged Man",
  death: "Death",
  temperance: "Temperance",
  the_devil: "The Devil",
  the_tower: "The Tower",
  the_star: "The Star",
  the_moon: "The Moon",
  the_sun: "The Sun",
  judgment: "Judgment",
  the_world: "The World",
  ace_of_wands: "Ace of Wands",
  two_of_wands: "Two of Wands",
  three_of_wands: "Three of Wands",
  four_of_wands: "Four of Wands",
  five_of_wands: "Five of Wands",
  six_of_wands: "Six of Wands",
  seven_of_wands: "Seven of Wands",
  eight_of_wands: "Eight of Wands",
  nine_of_wands: "Nine of Wands",
  ten_of_wands: "Ten of Wands",
  page_of_wands: "Page of Wands",
  knight_of_wands: "Knight of Wands",
  queen_of_wands: "Queen of Wands",
  king_of_wands: "King of Wands",
  ace_of_cups: "Ace of Cups",
  two_of_cups: "Two of Cups",
  three_of_cups: "Three of Cups",
  four_of_cups: "Four of Cups",
  five_of_cups: "Five of Cups",
  six_of_cups: "Six of Cups",
  seven_of_cups: "Seven of Cups",
  eight_of_cups: "Eight of Cups",
  nine_of_cups: "Nine of Cups",
  ten_of_cups: "Ten of Cups",
  page_of_cups: "Page of Cups",
  knight_of_cups: "Knight of Cups",
  queen_of_cups: "Queen of Cups",
  king_of_cups: "King of Cups",
  ace_of_swords: "Ace of Swords",
  two_of_swords: "Two of Swords",
  three_of_swords: "Three of Swords",
  four_of_swords: "Four of Swords",
  five_of_swords: "Five of Swords",
  six_of_swords: "Six of Swords",
  seven_of_swords: "Seven of Swords",
  eight_of_swords: "Eight of Swords",
  nine_of_swords: "Nine of Swords",
  ten_of_swords: "Ten of Swords",
  page_of_swords: "Page of Swords",
  knight_of_swords: "Knight of Swords",
  queen_of_swords: "Queen of Swords",
  king_of_swords: "King of Swords",
  ace_of_pentacles: "Ace of Pentacles",
  two_of_pentacles: "Two of Pentacles",
  three_of_pentacles: "Three of Pentacles",
  four_of_pentacles: "Four of Pentacles",
  five_of_pentacles: "Five of Pentacles",
  six_of_pentacles: "Six of Pentacles",
  seven_of_pentacles: "Seven of Pentacles",
  eight_of_pentacles: "Eight of Pentacles",
  nine_of_pentacles: "Nine of Pentacles",
  ten_of_pentacles: "Ten of Pentacles",
  page_of_pentacles: "Page of Pentacles",
  knight_of_pentacles: "Knight of Pentacles",
  queen_of_pentacles: "Queen of Pentacles",
  king_of_pentacles: "King of Pentacles",
} as const;

const ukrainian = {
  the_fool: "Дурак",
  the_magician: "Маг",
  the_high_priestess: "Жрица",
  the_empress: "Императрица",
  the_emperor: "Император",
  the_hierophant: "Иерофант",
  the_lovers: "Влюбленные",
  the_chariot: "Колесница",
  strength: "Сила",
  the_hermit: "Отшельник",
  wheel_of_fortune: "Колесо Фортуны",
  justice: "Справедливость",
  the_hanged_man: "Повешенный",
  death: "Смерть",
  temperance: "Умеренность",
  the_devil: "Дьявол",
  the_tower: "Башня",
  the_star: "Звезда",
  the_moon: "Луна",
  the_sun: "Солнце",
  judgment: "Суд",
  the_world: "Мир",
  ace_of_wands: "Туз Жезлов",
  two_of_wands: "Двойка Жезлов",
  three_of_wands: "Тройка Жезлов",
  four_of_wands: "Четверка Жезлов",
  five_of_wands: "Пятерка Жезлов",
  six_of_wands: "Шестерка Жезлов",
  seven_of_wands: "Семерка Жезлов",
  eight_of_wands: "Восьмерка Жезлов",
  nine_of_wands: "Девятка Жезлов",
  ten_of_wands: "Десятка Жезлов",
  page_of_wands: "Паж Жезлов",
  knight_of_wands: "Рыцарь Жезлов",
  queen_of_wands: "Королева Жезлов",
  king_of_wands: "Король Жезлов",
  ace_of_cups: "Туз Кубков",
  two_of_cups: "Двойка Кубков",
  three_of_cups: "Тройка Кубков",
  four_of_cups: "Четверка Кубков",
  five_of_cups: "Пятерка Кубков",
  six_of_cups: "Шестерка Кубков",
  seven_of_cups: "Семерка Кубков",
  eight_of_cups: "Восьмерка Кубков",
  nine_of_cups: "Девятка Кубков",
  ten_of_cups: "Десятка Кубков",
  page_of_cups: "Паж Кубков",
  knight_of_cups: "Рыцарь Кубков",
  queen_of_cups: "Королева Кубков",
  king_of_cups: "Король Кубков",
  ace_of_swords: "Туз Мечей",
  two_of_swords: "Двойка Мечей",
  three_of_swords: "Тройка Мечей",
  four_of_swords: "Четверка Мечей",
  five_of_swords: "Пятерка Мечей",
  six_of_swords: "Шестерка Мечей",
  seven_of_swords: "Семерка Мечей",
  eight_of_swords: "Восьмерка Мечей",
  nine_of_swords: "Девятка Мечей",
  ten_of_swords: "Десятка Мечей",
  page_of_swords: "Паж Мечей",
  knight_of_swords: "Рыцарь Мечей",
  queen_of_swords: "Королева Мечей",
  king_of_swords: "Король Мечей",
  ace_of_pentacles: "Туз Пентаклей",
  two_of_pentacles: "Двойка Пентаклей",
  three_of_pentacles: "Тройка Пентаклей",
  four_of_pentacles: "Четверка Пентаклей",
  five_of_pentacles: "Пятерка Пентаклей",
  six_of_pentacles: "Шестерка Пентаклей",
  seven_of_pentacles: "Семерка Пентаклей",
  eight_of_pentacles: "Восьмерка Пентаклей",
  nine_of_pentacles: "Девятка Пентаклей",
  ten_of_pentacles: "Десятка Пентаклей",
  page_of_pentacles: "Паж Пентаклей",
  knight_of_pentacles: "Рыцарь Пентаклей",
  queen_of_pentacles: "Королева Пентаклей",
  king_of_pentacles: "Король Пентаклей",
} as const;

const russian = {
  the_fool: "Дурень",
  the_magician: "Маг",
  the_high_priestess: "Жриця",
  the_empress: "Імператриця",
  the_emperor: "Імператор",
  the_hierophant: "Ієрофант",
  the_lovers: "Закохані",
  the_chariot: "Колісниця",
  strength: "Сила",
  the_hermit: "Відлюдник",
  wheel_of_fortune: "Колесо Фортуни",
  justice: "Справедливість",
  the_hanged_man: "Повішений",
  death: "Смерть",
  temperance: "Помірність",
  the_devil: "Диявол",
  the_tower: "Вежа",
  the_star: "Зірка",
  the_moon: "Місяць",
  the_sun: "Сонце",
  judgment: "Суд",
  the_world: "Світ",
  ace_of_wands: "Туз Жезлів",
  two_of_wands: "Двійка Жезлів",
  three_of_wands: "Трійка Жезлів",
  four_of_wands: "Четвірка Жезлів",
  five_of_wands: "П’ятірка Жезлів",
  six_of_wands: "Шістка Жезлів",
  seven_of_wands: "Сімка Жезлів",
  eight_of_wands: "Вісімка Жезлів",
  nine_of_wands: "Дев’ятка Жезлів",
  ten_of_wands: "Десятка Жезлів",
  page_of_wands: "Паж Жезлів",
  knight_of_wands: "Лицар Жезлів",
  queen_of_wands: "Королева Жезлів",
  king_of_wands: "Король Жезлів",
  ace_of_cups: "Туз Кубків",
  two_of_cups: "Двійка Кубків",
  three_of_cups: "Трійка Кубків",
  four_of_cups: "Четвірка Кубків",
  five_of_cups: "П’ятірка Кубків",
  six_of_cups: "Шістка Кубків",
  seven_of_cups: "Сімка Кубків",
  eight_of_cups: "Вісімка Кубків",
  nine_of_cups: "Дев’ятка Кубків",
  ten_of_cups: "Десятка Кубків",
  page_of_cups: "Паж Кубків",
  knight_of_cups: "Лицар Кубків",
  queen_of_cups: "Королева Кубків",
  king_of_cups: "Король Кубків",
  ace_of_swords: "Туз Мечів",
  two_of_swords: "Двійка Мечів",
  three_of_swords: "Трійка Мечів",
  four_of_swords: "Четвірка Мечів",
  five_of_swords: "П’ятірка Мечів",
  six_of_swords: "Шістка Мечів",
  seven_of_swords: "Сімка Мечів",
  eight_of_swords: "Вісімка Мечів",
  nine_of_swords: "Дев’ятка Мечів",
  ten_of_swords: "Десятка Мечів",
  page_of_swords: "Паж Мечів",
  knight_of_swords: "Лицар Мечів",
  queen_of_swords: "Королева Мечів",
  king_of_swords: "Король Мечів",
  ace_of_pentacles: "Туз Пентаклів",
  two_of_pentacles: "Двійка Пентаклів",
  three_of_pentacles: "Трійка Пентаклів",
  four_of_pentacles: "Четвірка Пентаклів",
  five_of_pentacles: "П’ятірка Пентаклів",
  six_of_pentacles: "Шістка Пентаклів",
  seven_of_pentacles: "Сімка Пентаклів",
  eight_of_pentacles: "Вісімка Пентаклів",
  nine_of_pentacles: "Дев’ятка Пентаклів",
  ten_of_pentacles: "Десятка Пентаклів",
  page_of_pentacles: "Паж Пентаклів",
  knight_of_pentacles: "Лицар Пентаклів",
  queen_of_pentacles: "Королева Пентаклів",
  king_of_pentacles: "Король Пентаклів",
} as const;

export const cards = {
  english: english,
  ukrainian: ukrainian,
  russian: russian,
};
